CPU ZED Docker
husarion/zed-docker pull request #14
Opened 2023-05-30 08:46 UTC by rafal-gorecki

2023-05-30 11:13 UTC, KmakD requested changes

2023-05-30 11:13 UTC, KmakD commented on Dockerfile.cpu
> +    apt clean && \
```suggestion
RUN apt-get update && apt install -y \
        git \
        libhidapi-libusb0 \
        libopencv-viz-dev \
        udev && \
    apt-get clean && \
```

2023-05-30 11:13 UTC, KmakD commented on Dockerfile.cpu
> +    source /opt/ros/$ROS_DISTRO/setup.bash && \
```suggestion
RUN apt-get update && \
    git clone -b ros1 https://github.com/husarion/zed_cpu.git src/zed_cpu && \
    source /opt/ros/$ROS_DISTRO/setup.bash && \
```

2023-05-30 11:13 UTC, KmakD commented on README.md
> +a) **Running with CUDA** (for `husarion/zed-desktop` or `husarion/zed-jetson` images)
```suggestion
#### Running with CUDA (for `husarion/zed-desktop` or `husarion/zed-jetson` images)
```
Thing to consider

2023-05-31 09:00 UTC, rafal-gorecki commented on README.md
> +a) **Running with CUDA** (for `husarion/zed-desktop` or `husarion/zed-jetson` images)
For me it is better to leave a) b), because they are two independent options. The headline is more suggestive of a step to take than the options. Tabs would be the best solution, but they are not supported. Additionalie there is a similar option befere. 

```md
  ### Get image
  **a) Building a Docker image**
    docker build -t <image_tag> -f <select_dockerfile> .

  **b) Pulling the Docker image**
    docker pull ${ZED_IMAGE}
```

2023-05-31 09:23 UTC, KmakD commented on README.md
> +a) **Running with CUDA** (for `husarion/zed-desktop` or `husarion/zed-jetson` images)
Ok :+1:

2023-05-31 09:26 UTC, KmakD approved these changes
I will merge after this pass: https://github.com/husarion/zed_cpu/pull/2

2023-06-02 11:13 UTC, merged